import { ChevronLeft, ChevronRight, TodayOutlined } from '@mui/icons-material';
import { Button, IconButton, MenuItem, Stack, TextField, ToggleButton, ToggleButtonGroup, Tooltip } from '@mui/material';
import type { CalendarFilters, DeliveryView } from '../types';

export function CalendarToolbar({ month, filters, view, plans, onMonth, onPrevious, onNext, onToday, onFilters, onView }: { month: string; filters: CalendarFilters; view: DeliveryView; plans: Array<{ id: string; name: string }>; onMonth: (value: string) => void; onPrevious: () => void; onNext: () => void; onToday: () => void; onFilters: (value: CalendarFilters) => void; onView: (value: DeliveryView) => void }) {
  const filter = (key: keyof CalendarFilters, value: string) => onFilters({ ...filters, [key]: value });
  return <Stack spacing={2} p={2} borderBottom={1} borderColor="divider"><Stack direction={{ xs: 'column', md: 'row' }} alignItems={{ md: 'center' }} gap={1}><Stack direction="row" alignItems="center"><Tooltip title="Previous month"><IconButton onClick={onPrevious} aria-label="Previous month"><ChevronLeft /></IconButton></Tooltip><TextField type="month" value={month} onChange={(event) => onMonth(event.target.value)} aria-label="Calendar month" /><Tooltip title="Next month"><IconButton onClick={onNext} aria-label="Next month"><ChevronRight /></IconButton></Tooltip></Stack><Button startIcon={<TodayOutlined />} onClick={onToday}>Today</Button><Stack flex={1} /><ToggleButtonGroup exclusive size="small" value={view} onChange={(_, value: DeliveryView | null) => value && onView(value)} aria-label="Calendar view"><ToggleButton value="month">Month</ToggleButton><ToggleButton value="week">Week</ToggleButton><ToggleButton value="list">List</ToggleButton></ToggleButtonGroup></Stack><Stack direction={{ xs: 'column', sm: 'row' }} gap={1.5} flexWrap="wrap"><TextField select label="Meal plan" value={filters.planId} onChange={(event) => filter('planId', event.target.value)} sx={{ minWidth: 170 }}><MenuItem value="">All plans</MenuItem>{plans.map((plan) => <MenuItem key={plan.id} value={plan.id}>{plan.name}</MenuItem>)}</TextField><TextField select label="Delivery status" value={filters.status} onChange={(event) => filter('status', event.target.value)} sx={{ minWidth: 170 }}><MenuItem value="">All statuses</MenuItem>{['SCHEDULED', 'OVERRIDE', 'PARTIAL', 'CLOSED', 'NO_DELIVERIES'].map((status) => <MenuItem key={status} value={status}>{status.replaceAll('_', ' ')}</MenuItem>)}</TextField><TextField select label="Has override" value={filters.hasOverride} onChange={(event) => filter('hasOverride', event.target.value)} sx={{ minWidth: 150 }}><MenuItem value="">Any</MenuItem><MenuItem value="yes">Yes</MenuItem><MenuItem value="no">No</MenuItem></TextField><TextField select label="Holiday / closure" value={filters.closure} onChange={(event) => filter('closure', event.target.value)} sx={{ minWidth: 170 }}><MenuItem value="">Any</MenuItem><MenuItem value="yes">Closure only</MenuItem><MenuItem value="no">Exclude closures</MenuItem></TextField></Stack></Stack>;
}

