import { ChevronLeft, ChevronRight, TodayOutlined } from '@mui/icons-material';
import { Box, Button, Chip, IconButton, MenuItem, Stack, TextField, ToggleButton, ToggleButtonGroup, Tooltip, Typography } from '@mui/material';
import type { CalendarFilters, DeliveryView } from '../types';

export function CalendarToolbar({ month, filters, view, plans, onMonth, onPrevious, onNext, onToday, onFilters, onView }: { month: string; filters: CalendarFilters; view: DeliveryView; plans: Array<{ id: string; name: string }>; onMonth: (value: string) => void; onPrevious: () => void; onNext: () => void; onToday: () => void; onFilters: (value: CalendarFilters) => void; onView: (value: DeliveryView) => void }) {
  const filter = (key: keyof CalendarFilters, value: string) => onFilters({ ...filters, [key]: value });
  const activeFilters = Object.values(filters).filter(Boolean).length;
  const legend = [{ label: 'Orders scheduled', color: '#2E7D43' }, { label: 'No orders', color: '#82908B' }];
  return <Stack spacing={2} p={2} borderBottom={1} borderColor="divider"><Stack direction={{ xs: 'column', md: 'row' }} alignItems={{ md: 'center' }} gap={1}><Stack direction="row" alignItems="center"><Tooltip title="Previous month"><IconButton onClick={onPrevious} aria-label="Previous month"><ChevronLeft /></IconButton></Tooltip><TextField type="month" value={month} onChange={(event) => onMonth(event.target.value)} aria-label="Calendar month" /><Tooltip title="Next month"><IconButton onClick={onNext} aria-label="Next month"><ChevronRight /></IconButton></Tooltip></Stack><Button startIcon={<TodayOutlined />} onClick={onToday}>Today</Button><Stack flex={1} /><ToggleButtonGroup exclusive size="small" value={view} onChange={(_, value: DeliveryView | null) => value && onView(value)} aria-label="Calendar view"><ToggleButton value="month">Month</ToggleButton><ToggleButton value="week">Week</ToggleButton><ToggleButton value="list">List</ToggleButton></ToggleButtonGroup></Stack><Stack direction={{ xs: 'column', sm: 'row' }} gap={1.5} flexWrap="wrap"><TextField select label="Meal plan" value={filters.planId} onChange={(event) => filter('planId', event.target.value)} sx={{ minWidth: 170 }}><MenuItem value="">All plans</MenuItem>{plans.map((plan) => <MenuItem key={plan.id} value={plan.id}>{plan.name}</MenuItem>)}</TextField><TextField select label="Order status" value={filters.status} onChange={(event) => filter('status', event.target.value)} sx={{ minWidth: 170 }}><MenuItem value="">All statuses</MenuItem>{['CONFIRMED', 'PAUSED', 'CANCELLED'].map((status) => <MenuItem key={status} value={status}>{status}</MenuItem>)}</TextField>{activeFilters > 0 && <Chip label={`Clear ${activeFilters} ${activeFilters === 1 ? 'filter' : 'filters'}`} onDelete={() => onFilters({ planId: '', status: '', hasOverride: '', closure: '' })} onClick={() => onFilters({ planId: '', status: '', hasOverride: '', closure: '' })} variant="outlined" sx={{ alignSelf: 'center' }} />}</Stack><Stack direction="row" alignItems="center" gap={2} flexWrap="wrap"><Typography variant="caption" fontWeight={800} color="text.secondary">STATUS</Typography>{legend.map((item) => <Stack key={item.label} direction="row" alignItems="center" gap={0.6}><Box sx={{ width: 8, height: 8, borderRadius: '50%', bgcolor: item.color }} /><Typography variant="caption" color="text.secondary">{item.label}</Typography></Stack>)}</Stack></Stack>;
}
