import { LocalShippingOutlined, PeopleOutline, SwapHorizOutlined } from '@mui/icons-material';
import { Box, Chip, LinearProgress, Stack, Tooltip, Typography } from '@mui/material';
import { format, isBefore, isSameDay, parseISO, startOfDay } from 'date-fns';
import type { DeliveryCalendarDay } from '../types';
import { colors } from '@/theme/theme';

const statuses: Record<DeliveryCalendarDay['operationalStatus'], { label: string; color: 'success' | 'warning' | 'error' | 'default' | 'info'; tone: string; tint: string }> = {
  SCHEDULED: { label: 'Scheduled', color: 'success', tone: '#2E7D43', tint: '#F1F8F3' },
  OVERRIDE: { label: 'Menu Override', color: 'warning', tone: colors.orange, tint: '#FFF6F3' },
  CLOSED: { label: 'Closed', color: 'error', tone: colors.jasper, tint: '#FFF3F5' },
  NO_DELIVERIES: { label: 'No Deliveries', color: 'default', tone: '#82908B', tint: '#F8FAF9' },
  PARTIAL: { label: 'Special Schedule', color: 'info', tone: '#1675A9', tint: '#F1F8FC' },
};
const statusProps = (status: DeliveryCalendarDay['operationalStatus']) => statuses[status];

export function CalendarDayCell({ day, compact = false, maxDeliveries, onSelect }: { day: DeliveryCalendarDay; compact?: boolean; maxDeliveries: number; onSelect: (date: string) => void }) {
  const status = statusProps(day.operationalStatus);
  const parsedDate = parseISO(day.date);
  const past = isBefore(parsedDate, startOfDay(new Date()));
  const today = isSameDay(parsedDate, new Date());
  const content = day.operationalStatus === 'CLOSED' ? <Stack spacing={0.5}><Typography fontWeight={800} color="error.main">Kitchen closed</Typography><Typography variant="caption" color="text.secondary" noWrap>{day.holidayName ?? day.closureReason}</Typography><Typography variant="caption" fontWeight={700}>No orders scheduled</Typography></Stack> : <><Stack direction="row" gap={compact ? 3 : 0} justifyContent={compact ? 'flex-start' : 'space-between'} flexWrap="wrap"><Stack direction="row" alignItems="center" gap={0.6}><LocalShippingOutlined sx={{ fontSize: 17, color: status.tone }} /><Typography variant="body2"><strong>{day.totalDeliveries}</strong> orders</Typography></Stack><Stack direction="row" alignItems="center" gap={0.6}><PeopleOutline sx={{ fontSize: 17, color: 'text.secondary' }} /><Typography variant="body2"><strong>{day.totalCustomers}</strong> customers</Typography></Stack></Stack>{day.totalDeliveries > 0 && <Tooltip title={`${Math.round((day.totalDeliveries / maxDeliveries) * 100)}% of this month's peak daily volume`}><LinearProgress variant="determinate" value={(day.totalDeliveries / maxDeliveries) * 100} sx={{ height: 5, borderRadius: 3, bgcolor: '#E8EEEB', '& .MuiLinearProgress-bar': { bgcolor: status.tone, borderRadius: 3 } }} /></Tooltip>}{day.overrideCount > 0 && <Stack direction="row" alignItems="center" gap={0.5}><SwapHorizOutlined sx={{ fontSize: 16, color: 'warning.main' }} /><Typography variant="caption" fontWeight={800} color="warning.main">{day.overrideCount} menu {day.overrideCount === 1 ? 'change' : 'changes'}</Typography></Stack>}</>;
  return <Box component="button" type="button" onClick={() => onSelect(day.date)} aria-label={`Open deliveries for ${format(parsedDate, 'EEEE, d MMMM yyyy')}`} sx={{ appearance: 'none', position: 'relative', width: '100%', minHeight: compact ? 96 : 150, p: compact ? 1.5 : 1.25, border: 0, borderInlineEnd: compact ? 0 : 1, borderBottom: 1, borderColor: 'divider', bgcolor: today ? '#F1F8F4' : 'background.paper', color: 'text.primary', textAlign: 'start', cursor: 'pointer', opacity: past ? 0.82 : 1, overflow: 'hidden', transition: 'background-color .16s ease, box-shadow .16s ease, transform .16s ease', '&::before': { content: '""', position: 'absolute', top: 0, insetInlineStart: 0, bottom: 0, width: compact ? 4 : 3, bgcolor: status.tone, opacity: day.operationalStatus === 'NO_DELIVERIES' ? 0.35 : 1 }, '&:hover': { bgcolor: status.tint, boxShadow: 'inset 0 0 0 1px rgba(23,53,45,.08)', zIndex: 1, '& .calendar-open-hint': { opacity: 1, transform: 'translateX(0)' } }, '&:focus-visible': { zIndex: 2 } }}><Stack spacing={compact ? 1 : 0.9}><Stack direction="row" justifyContent="space-between" alignItems="center" gap={1}><Stack direction="row" alignItems="center" gap={0.75}><Box sx={{ width: 29, height: 29, display: 'grid', placeItems: 'center', borderRadius: '50%', bgcolor: today ? 'primary.main' : 'transparent', color: today ? 'common.white' : 'text.primary', fontWeight: 800 }}>{format(parsedDate, compact ? 'd' : 'd')}</Box>{compact && <Box><Typography fontWeight={800}>{format(parsedDate, 'EEEE')}</Typography><Typography variant="caption" color="text.secondary">{format(parsedDate, 'MMMM yyyy')}</Typography></Box>}</Stack><Tooltip title={status.label}><Chip size="small" label={status.label} color={status.color} variant={status.color === 'default' ? 'outlined' : 'filled'} sx={{ maxWidth: compact ? 150 : 126, height: 24, '& .MuiChip-label': { px: 1, fontSize: 11, fontWeight: 750 } }} /></Tooltip></Stack>{content}</Stack></Box>;
}
