import { LocalShippingOutlined, PeopleOutline, SwapHorizOutlined } from '@mui/icons-material';
import { Box, LinearProgress, Stack, Tooltip, Typography } from '@mui/material';
import { format, isSameDay, parseISO } from 'date-fns';
import type { DeliveryCalendarDay } from '../types';
import { colors } from '@/theme/theme';

const statuses: Record<DeliveryCalendarDay['operationalStatus'], { label: string; color: 'success' | 'warning' | 'error' | 'default' | 'info'; tone: string; tint: string }> = {
  SCHEDULED: { label: 'Scheduled', color: 'success', tone: '#2E7D43', tint: '#F1F8F3' },
  OVERRIDE: { label: 'Menu Override', color: 'warning', tone: colors.orange, tint: '#FFF6F3' },
  CLOSED: { label: 'Closed', color: 'error', tone: colors.jasper, tint: '#FFF3F5' },
  NO_DELIVERIES: { label: 'No Deliveries', color: 'default', tone: '#82908B', tint: '#F8FAF9' },
  PARTIAL: { label: 'Special Schedule', color: 'info', tone: '#1675A9', tint: '#F1F8FC' },
};
const statusProps = (status: DeliveryCalendarDay['operationalStatus']) => statuses[status];

export function CalendarDayCell({ day, compact = false, maxDeliveries, onSelect }: { day: DeliveryCalendarDay; compact?: boolean; maxDeliveries: number; onSelect: (date: string) => void }) {
  const status = statusProps(day.operationalStatus);
  const parsedDate = parseISO(day.date);
  const today = isSameDay(parsedDate, new Date());
  const content = day.operationalStatus === 'CLOSED' ? <Stack spacing={0.35}><Typography variant="body2" fontWeight={800} color="error.main">Kitchen closed</Typography><Typography variant="caption" color="text.secondary" noWrap>{day.holidayName ?? day.closureReason}</Typography></Stack> : <><Stack direction={compact ? 'row' : 'column'} gap={compact ? 3 : 0.65} flexWrap="wrap"><Stack direction="row" alignItems="center" gap={0.55}><LocalShippingOutlined sx={{ fontSize: 17, color: day.totalDeliveries ? status.tone : 'text.disabled' }} /><Typography variant="body2" fontWeight={day.totalDeliveries ? 750 : 500} color={day.totalDeliveries ? 'text.primary' : 'text.secondary'}>{day.totalDeliveries} <Box component="span" sx={{ fontWeight: 500, color: 'text.secondary' }}>orders</Box></Typography></Stack><Stack direction="row" alignItems="center" gap={0.55}><PeopleOutline sx={{ fontSize: 17, color: 'text.disabled' }} /><Typography variant="body2" fontWeight={day.totalCustomers ? 750 : 500} color={day.totalCustomers ? 'text.primary' : 'text.secondary'}>{day.totalCustomers} <Box component="span" sx={{ fontWeight: 500, color: 'text.secondary' }}>customers</Box></Typography></Stack></Stack>{day.totalDeliveries > 0 && <Tooltip title={`${Math.round((day.totalDeliveries / maxDeliveries) * 100)}% of this month's peak daily volume`}><LinearProgress variant="determinate" value={(day.totalDeliveries / maxDeliveries) * 100} sx={{ height: 4, borderRadius: 3, bgcolor: '#E8EEEB', '& .MuiLinearProgress-bar': { bgcolor: status.tone, borderRadius: 3 } }} /></Tooltip>}{day.overrideCount > 0 && <Stack direction="row" alignItems="center" gap={0.5}><SwapHorizOutlined sx={{ fontSize: 16, color: 'warning.main' }} /><Typography variant="caption" fontWeight={800} color="warning.main">{day.overrideCount} menu {day.overrideCount === 1 ? 'change' : 'changes'}</Typography></Stack>}</>;
  return <Box component="button" type="button" onClick={() => onSelect(day.date)} aria-label={`Open deliveries for ${format(parsedDate, 'EEEE, d MMMM yyyy')}`} sx={{ appearance: 'none', position: 'relative', width: '100%', minHeight: compact ? 96 : 130, p: compact ? 1.5 : 1.25, border: 1, borderColor: today ? '#CFE5D7' : '#E8ECEA', borderRadius: compact ? 0 : 1.25, bgcolor: today ? '#EAF6EF' : 'background.paper', color: 'text.primary', textAlign: 'start', cursor: 'pointer', overflow: 'hidden', boxShadow: compact ? 'none' : '0 1px 4px rgba(23,53,45,.045)', transition: 'background-color .16s ease, box-shadow .16s ease, transform .16s ease', '&::before': { content: '""', position: 'absolute', top: 0, insetInlineStart: 0, bottom: 0, width: compact ? 4 : 0, bgcolor: status.tone, opacity: day.operationalStatus === 'NO_DELIVERIES' ? 0 : 1 }, '&:hover': { bgcolor: status.tint, borderColor: 'rgba(23,53,45,.2)', boxShadow: '0 4px 12px rgba(23,53,45,.09)', transform: compact ? 'none' : 'translateY(-1px)', zIndex: 1, '& .calendar-status': { color: status.tone } }, '&:focus-visible': { zIndex: 2 } }}><Stack spacing={compact ? 1 : 1.05}><Stack direction="row" justifyContent="space-between" alignItems="center" gap={0.5}><Stack direction="row" alignItems="center" gap={0.75}><Box sx={{ width: 28, height: 28, display: 'grid', placeItems: 'center', borderRadius: '50%', bgcolor: today ? 'primary.main' : 'transparent', color: today ? 'common.white' : 'text.primary', fontWeight: 800, fontSize: 14 }}>{format(parsedDate, 'd')}</Box>{compact && <Box><Typography fontWeight={800}>{format(parsedDate, 'EEEE')}</Typography><Typography variant="caption" color="text.secondary">{format(parsedDate, 'MMMM yyyy')}</Typography></Box>}</Stack><Tooltip title={status.label}><Stack className="calendar-status" direction="row" alignItems="center" gap={0.55} sx={{ color: status.color === 'default' ? 'text.secondary' : status.tone, minWidth: 0 }}><Box sx={{ width: 6, height: 6, flex: '0 0 auto', borderRadius: '50%', bgcolor: status.tone, opacity: status.color === 'default' ? 0.55 : 1 }} /><Typography variant="caption" fontWeight={800} noWrap>{status.label}</Typography></Stack></Tooltip></Stack>{content}</Stack></Box>;
}
