import { Add, MoreHoriz, Search } from '@mui/icons-material';
import { Box, Button, Card, IconButton, InputAdornment, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField, Typography } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { plansApi } from '@/api/plansApi';
import { RoleGuard } from '@/auth/RoleGuard';
import { StatusChip } from '@/components/common/StatusChip';
import { EmptyState, ErrorState, LoadingState } from '@/components/feedback/PageState';
export function PlanListPage(){const [page,setPage]=useState(0);const [search,setSearch]=useState('');const navigate=useNavigate();const query=useQuery({queryKey:['plans',{page,search}],queryFn:({signal})=>plansApi.list({page:page+1,pageSize:25,search:search||undefined},signal)});return <Stack spacing={3}><Stack direction="row" justifyContent="space-between"><Box><Typography variant="h1">Meal plan templates</Typography><Typography color="text.secondary">Build, validate, price, and publish customer meal programmes.</Typography></Box><RoleGuard allowedRoles={['Dietitian']}><Button component={Link} to="/meal-plans/new" variant="contained" startIcon={<Add/>}>Create plan</Button></RoleGuard></Stack><Card><Box p={2}><TextField value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search plan code or name" slotProps={{input:{startAdornment:<InputAdornment position="start"><Search/></InputAdornment>}}}/></Box>{query.isLoading?<Box p={2}><LoadingState/></Box>:query.isError?<Box p={2}><ErrorState message="Unable to load meal plans." onRetry={()=>void query.refetch()}/></Box>:!query.data?.items.length?<EmptyState title="No plan templates found"/>:<TableContainer><Table><TableHead><TableRow>{['Code','Name','Plan type','Duration','Customizable','Published','Active','Validity','Price from','Updated','Actions'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{query.data.items.map(p=><TableRow key={p.id}><TableCell>{p.code}</TableCell><TableCell>{p.nameEn}<Typography variant="caption" display="block" dir="rtl">{p.nameAr}</Typography></TableCell><TableCell>{p.planType}</TableCell><TableCell>{p.durationDays} days</TableCell><TableCell>{p.customizable?'Yes':'No'}</TableCell><TableCell><StatusChip label={p.published?'Published':'Draft'}/></TableCell><TableCell><StatusChip label={p.active?'Active':'Inactive'}/></TableCell><TableCell>{p.validFrom||'Open'} – {p.validUntil||'Open'}</TableCell><TableCell>{p.priceFrom===undefined?'—':`QAR ${p.priceFrom}`}</TableCell><TableCell>{new Date(p.updatedAt).toLocaleDateString()}</TableCell><TableCell><IconButton onClick={()=>navigate(`/meal-plans/${p.id}/edit`)} aria-label="Plan actions"><MoreHoriz/></IconButton></TableCell></TableRow>)}</TableBody></Table></TableContainer>}<TablePagination component="div" count={query.data?.totalCount??0} page={page} rowsPerPage={25} onPageChange={(_,v)=>setPage(v)} rowsPerPageOptions={[25]}/></Card></Stack>}
