import { Add, EditOutlined, ToggleOffOutlined, ToggleOnOutlined } from '@mui/icons-material';
import { Alert, Box, Button, Card, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, MenuItem, Snackbar, Stack, Switch, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Tooltip, Typography, FormControlLabel } from '@mui/material';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useMemo, useState } from 'react';
import { plansApi } from '@/api/plansApi';
import { packageOptionsApi, subscriptionPricingApi, type MealPlanPrice, type MealPlanPriceInput } from '@/api/subscriptionConfigurationApi';
import { queryClient } from '@/app/queryClient';
import { StatusChip } from '@/components/common/StatusChip';
import { ErrorState, LoadingState } from '@/components/feedback/PageState';

type ActiveFilter = 'all' | 'active' | 'inactive';
const money = (value: number, currency: string) => new Intl.NumberFormat('en-QA', { style: 'currency', currency, maximumFractionDigits: 2 }).format(value);

export function SubscriptionPlanPricingPage() {
  const [mealPlanId, setMealPlanId] = useState('');
  const [durationId, setDurationId] = useState('');
  const [active, setActive] = useState<ActiveFilter>('all');
  const [dialog, setDialog] = useState<MealPlanPrice | 'new' | null>(null);
  const [statusTarget, setStatusTarget] = useState<MealPlanPrice | null>(null);
  const [notice, setNotice] = useState('');
  const plans = useQuery({ queryKey: ['meal-plans', 'pricing-lookup'], queryFn: ({ signal }) => plansApi.list({ page: 1, pageSize: 100 }, signal) });
  const durations = useQuery({ queryKey: ['durations', 'lookup'], queryFn: ({ signal }) => subscriptionPricingApi.durations(signal) });
  const packages = useQuery({ queryKey: ['package-options', 'pricing-lookup'], queryFn: ({ signal }) => packageOptionsApi.list({ page: 1, pageSize: 100, isActive: true }, signal) });
  const prices = useQuery({ queryKey: ['meal-plan-prices', mealPlanId, durationId, active], queryFn: ({ signal }) => subscriptionPricingApi.list({ page: 1, pageSize: 100, mealPlanId: mealPlanId || undefined, durationId: durationId || undefined, isActive: active === 'all' ? undefined : active === 'active' }, signal) });
  const save = useMutation({ mutationFn: ({ id, body }: { id?: string; body: MealPlanPriceInput }) => id ? subscriptionPricingApi.update(id, body) : subscriptionPricingApi.create(body), onSuccess: async (_, value) => { setDialog(null); setNotice(value.id ? 'Price updated successfully.' : 'Price added successfully.'); await queryClient.invalidateQueries({ queryKey: ['meal-plan-prices'] }); } });
  const status = useMutation({ mutationFn: (price: MealPlanPrice) => subscriptionPricingApi.update(price.id, { mealPlanId: price.mealPlanId, durationId: price.durationId, packageOptionId: price.packageOptionId, price: price.price, currency: price.currency, isActive: !price.isActive }), onSuccess: async (_, price) => { setStatusTarget(null); setNotice(`Price ${price.isActive ? 'deactivated' : 'activated'} successfully.`); await queryClient.invalidateQueries({ queryKey: ['meal-plan-prices'] }); } });
  const planItems = plans.data?.items ?? [], durationItems = durations.data ?? [], packageItems = packages.data?.items ?? [], priceItems = prices.data?.items ?? [];
  const selectedPlan = planItems.find((item) => item.id === mealPlanId)?.nameEn;
  const selectedDuration = durationItems.find((item) => item.id === durationId)?.name;

  return <Stack spacing={2.5}>
    <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={2}><Box><Typography variant="h2">Plan Pricing</Typography><Typography color="text.secondary">Set a price for each meal plan, duration, and package option.</Typography></Box><Button variant="contained" startIcon={<Add />} onClick={() => setDialog('new')}>Add Price</Button></Stack>
    {(save.isError || status.isError) && <Alert severity="error">The pricing change could not be saved. It may duplicate an active price for the same plan, duration, and package.</Alert>}
    <Card sx={{ p: 2.5 }}><Grid container spacing={2}><Grid size={{ xs: 12, md: 5 }}><TextField select fullWidth label="Meal Plan" value={mealPlanId} onChange={(e) => setMealPlanId(e.target.value)}><MenuItem value="">All meal plans</MenuItem>{planItems.map((plan) => <MenuItem value={plan.id} key={plan.id}>{plan.nameEn}</MenuItem>)}</TextField></Grid><Grid size={{ xs: 12, md: 4 }}><TextField select fullWidth label="Duration" value={durationId} onChange={(e) => setDurationId(e.target.value)}><MenuItem value="">All durations</MenuItem>{durationItems.map((duration) => <MenuItem value={duration.id} key={duration.id}>{duration.name}</MenuItem>)}</TextField></Grid><Grid size={{ xs: 12, md: 3 }}><TextField select fullWidth label="Status" value={active} onChange={(e) => setActive(e.target.value as ActiveFilter)}><MenuItem value="all">All</MenuItem><MenuItem value="active">Active</MenuItem><MenuItem value="inactive">Inactive</MenuItem></TextField></Grid></Grid></Card>
    {(selectedPlan || selectedDuration) && <Typography variant="h3">{selectedPlan ?? 'All meal plans'} · {selectedDuration ?? 'All durations'}</Typography>}
    <Card>{prices.isLoading ? <Box p={3}><LoadingState /></Box> : prices.isError ? <Box p={3}><ErrorState message="Unable to load plan prices." onRetry={() => void prices.refetch()} /></Box> : !priceItems.length ? <Box textAlign="center" py={6}><Typography variant="h3">No prices match these filters</Typography><Typography color="text.secondary" mt={1}>Add a price for a package option to get started.</Typography></Box> : <TableContainer><Table sx={{ minWidth: 780 }}><TableHead><TableRow><TableCell>Meal Plan</TableCell><TableCell>Duration</TableCell><TableCell>Package</TableCell><TableCell>Price</TableCell><TableCell>Status</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{priceItems.map((price) => <TableRow hover key={price.id}><TableCell>{price.mealPlanName}</TableCell><TableCell>{price.durationName}</TableCell><TableCell><Typography fontWeight={700}>{price.packageOptionName}</Typography></TableCell><TableCell>{money(price.price, price.currency)}</TableCell><TableCell><StatusChip label={price.isActive ? 'Active' : 'Inactive'} /></TableCell><TableCell align="right"><Tooltip title="Edit price"><IconButton color="primary" aria-label={`Edit ${price.packageOptionName} price`} onClick={() => setDialog(price)}><EditOutlined /></IconButton></Tooltip><Tooltip title={price.isActive ? 'Deactivate price' : 'Activate price'}><IconButton color={price.isActive ? 'warning' : 'success'} aria-label={`${price.isActive ? 'Deactivate' : 'Activate'} ${price.packageOptionName} price`} onClick={() => setStatusTarget(price)}>{price.isActive ? <ToggleOffOutlined /> : <ToggleOnOutlined />}</IconButton></Tooltip></TableCell></TableRow>)}</TableBody></Table></TableContainer>}</Card>
    {dialog && <PriceDialog item={dialog === 'new' ? undefined : dialog} plans={planItems} durations={durationItems} packages={packageItems} existing={priceItems} pending={save.isPending} onClose={() => { setDialog(null); save.reset(); }} onSave={(body) => save.mutate({ id: dialog === 'new' ? undefined : dialog.id, body })} />}
    <Dialog open={!!statusTarget} onClose={() => !status.isPending && setStatusTarget(null)} maxWidth="xs" fullWidth><DialogTitle>{statusTarget?.isActive ? 'Deactivate price?' : 'Activate price?'}</DialogTitle><DialogContent><Typography>{statusTarget?.isActive ? 'This price will no longer be offered to new subscriptions. Historical customer order values will not change.' : 'This price will become available for new subscriptions.'}</Typography></DialogContent><DialogActions><Button onClick={() => setStatusTarget(null)}>Cancel</Button><Button variant="contained" color={statusTarget?.isActive ? 'warning' : 'primary'} onClick={() => statusTarget && status.mutate(statusTarget)}>Confirm</Button></DialogActions></Dialog>
    <Snackbar open={!!notice} autoHideDuration={4000} message={notice} onClose={() => setNotice('')} />
  </Stack>;
}

function PriceDialog({ item, plans, durations, packages, existing, pending, onClose, onSave }: { item?: MealPlanPrice; plans: Array<{ id: string; nameEn: string }>; durations: Array<{ id: string; name: string }>; packages: Array<{ id: string; name: string }>; existing: MealPlanPrice[]; pending: boolean; onClose: () => void; onSave: (body: MealPlanPriceInput) => void }) {
  const [values, setValues] = useState<MealPlanPriceInput>(item ? { mealPlanId: item.mealPlanId, durationId: item.durationId, packageOptionId: item.packageOptionId, price: item.price, currency: item.currency, isActive: item.isActive } : { mealPlanId: '', durationId: '', packageOptionId: '', price: 0, currency: 'QAR', isActive: true });
  const [submitted, setSubmitted] = useState(false);
  const duplicate = useMemo(() => values.isActive && existing.some((price) => price.id !== item?.id && price.isActive && price.mealPlanId === values.mealPlanId && price.durationId === values.durationId && price.packageOptionId === values.packageOptionId), [existing, item?.id, values]);
  const invalid = !values.mealPlanId || !values.durationId || !values.packageOptionId || !(values.price > 0) || !values.currency.trim() || duplicate;
  return <Dialog open fullWidth maxWidth="sm" onClose={() => !pending && onClose()}><DialogTitle>{item ? 'Edit Price' : 'Add Price'}</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{duplicate && <Alert severity="error">An active price already exists for this meal plan, duration, and package.</Alert>}<TextField required select label="Meal Plan" value={values.mealPlanId} error={submitted && !values.mealPlanId} helperText={submitted && !values.mealPlanId ? 'Meal plan is required.' : undefined} onChange={(e) => setValues({ ...values, mealPlanId: e.target.value })}>{plans.map((plan) => <MenuItem value={plan.id} key={plan.id}>{plan.nameEn}</MenuItem>)}</TextField><TextField required select label="Duration" value={values.durationId} error={submitted && !values.durationId} helperText={submitted && !values.durationId ? 'Duration is required.' : undefined} onChange={(e) => setValues({ ...values, durationId: e.target.value })}>{durations.map((duration) => <MenuItem value={duration.id} key={duration.id}>{duration.name}</MenuItem>)}</TextField><TextField required select label="Package Option" value={values.packageOptionId} error={submitted && !values.packageOptionId} helperText={submitted && !values.packageOptionId ? 'Package is required.' : undefined} onChange={(e) => setValues({ ...values, packageOptionId: e.target.value })}>{packages.map((option) => <MenuItem value={option.id} key={option.id}>{option.name}</MenuItem>)}</TextField><Grid container spacing={2}><Grid size={{ xs: 8 }}><TextField required fullWidth type="number" label="Price" value={values.price} error={submitted && !(values.price > 0)} helperText={submitted && !(values.price > 0) ? 'Price must be greater than zero.' : undefined} onChange={(e) => setValues({ ...values, price: Number(e.target.value) })} /></Grid><Grid size={{ xs: 4 }}><TextField required fullWidth label="Currency" value={values.currency} error={submitted && !values.currency.trim()} onChange={(e) => setValues({ ...values, currency: e.target.value.toUpperCase() })} /></Grid></Grid><FormControlLabel control={<Switch checked={values.isActive} onChange={(_, checked) => setValues({ ...values, isActive: checked })} />} label="Active" /><Alert severity="info">Changing this master price does not alter historical customer order values.</Alert></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={pending} onClick={() => { setSubmitted(true); if (!invalid) onSave({ ...values, currency: values.currency.trim().toUpperCase() }); }}>{pending ? 'Saving…' : 'Save Price'}</Button></DialogActions></Dialog>;
}
